name: Build and Deploy TEXTIL_COILL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: TEXTIL_COILL
        run: npm ci
      
      - name: Build
        working-directory: TEXTIL_COILL
        run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TEXTIL_COILL/dist
          cname: hectorjhon.com
          force_orphan: true